### ISSUE TITLE
Wifi Hotspot usually doesn't start

### ISSUE THREAD

**Issue by utopalex** [tesla-android/issue-tracker#103]
Thanks for your work. I tried the latest version and noticed the Wifi-Hotspot is very unstable.
It is visible in the status bar on top of Android interface and says enabled. wlan0 interface is up. However, none of my wifi devices find the hotspot.
1 out of 10 times however it shows up eventually, but usually after a very long time of starting the Raspberry Pi 4.

Could this be an issue with Wifi region configuration and frequencies? I tried setting locale to German/Germany, but it doesn't seem to make a difference.

RPI4 is on the latest EEPROM from Jan 2022.
Whenever it manages to start, I can also connect to 9.9.0.1 - however it hangs on afterwards and doesn't show anything from the Camera interface. Not sure if this connected.

Any way to debug what Hotspot is doing? Is it using wpa_supplicant?

**Comment by earthwormjimwow** [comment]
Can you show a picture of your Pi?  Does it have a heatsink or case?

**Comment by mikegapinski** [comment]
Most likely fixed with 2022.44.x, capture card was the problem here
