### ISSUE TITLE
2022.44.1 Image Size Issue with 64GB (not GiB) SD Cards

### ISSUE THREAD

**Issue by earthwormjimwow** [tesla-android/issue-tracker#108]
It seems the partition size for the single image install exceeds 64GB (as in powers of 10), it's 64,088,965,120 bytes.  Most manufacturers sell SD cards using powers of 10, so a 64GB SD card will have 64,000,000,000 bytes available, or possibly even slightly less if they resort to rounding.  It's not possible to flash the various 64GB cards I have on hand with this image file, since it exceeds the size of all of the cards.

**Comment by mikegapinski** [comment]
2022.44.2 on the way with the fix for this, sorry for the trouble
