### ISSUE TITLE
Serve UI on all (functionally) interfaces

### ISSUE THREAD

**Issue by adrum** [tesla-android/issue-tracker#109]
I plugged my pi in to my switch for ethernet connectivity, but the UI appears to be only accessible when on the Pi's wifi network. The UI is looking for 9.9.0.1 as the host. Would be nice if the resources loaded by the webpage were relative to the initial page. aka the LAN IP on my network.

The initial webpage loads fine, but the web socket connection fails. The UI reads a message "Virtual touchscreen not available. Wait for Android to boot up."

**Comment by mikegapinski** [comment]
I don't see a point in this functionally - the car won't be able to reach this on standard LAN IP's

**Comment by adrum** [comment]
@mikegapinski That’s fair. It was a temporary setup to connect the Pi to internet, since I’m running Offline mode. It just made it easier to setup accounts, downloads, etc using my computer. I imagine I will do OTA updates like this in the future, too.

**Comment by mikegapinski** [comment]
This makes sense + it might be useful for me when testing locally. Could you make an issue in the flutter app repo? I'll pick it up from there
