### ISSUE TITLE
Tesla can not connect to Android WiFi Hotdpot

### ISSUE THREAD

**Issue by electricAntEater32** [tesla-android/issue-tracker#110]
In   2022.44.1  the tesla can not connect to android os Wi-Fi hotspot. But my phone & iPad have no issue. Message from tesla is usually about not being able to get an ip from dhcp server & sometimes “the internet is unreachable. Please check your firewall settings & internet connection”. Tesla firmware 2022.36.5 . No lte modem. Car is located in California , USA.  I didn’t experience this issue in first release of single pi setup.

**Comment by mikegapinski** [comment]
2022.44.2 on the way, forgot to include one file in the image
