### ISSUE TITLE
UI randomly flashes in 2022.44.1 

### ISSUE THREAD

**Issue by earthwormjimwow** [tesla-android/issue-tracker#112]
I'm getting random flashes or flickering in the UI with 2022.44.1, I only use Carplay so I haven't determined if it happens outside of Carplay.   At random, the entire image being streamed transitions to white for several frames, then transitions back to displaying what it should be streaming from the Pi.  

I do not know if this is an issue with the update, or if this is an issue with Autokit (out of your control).  I could not get Autokit to update today, since their servers are complete garbage and constantly time out.

**Comment by mikegapinski** [comment]
Please update the app + make sure to use a decent power source.

It can also help to switch the charging mode to weak in AutoKit settings, this reduces the power consumption

**Comment by earthwormjimwow** [comment]
Issue persists in 2022.44.2.  Autokit was updated, I always enable low power charging, I have more than adequate power (3A at 5V), short cabl, especially since the same power supply has worked for all previous releases and even powering two Pis, and I'm using a short USB-C cable.

The banner, showing the version in the upper left corner does not flash, if that helps for figuring out a cause.

Here's a video I recorded prior to updating to 2022.44.2, but it looks the same in 2022.44.1 andd 2022.44.2.

Car is currently on 2022.36.5

**Comment by earthwormjimwow** [comment]
Issue seems to have fixed itself?  I did make one change, I increased the overclock on the Pi to 2GHz and upped the voltage.

**Comment by mikegapinski** [comment]
Remove the overclock entirely, I don't use it on my Pi right now and it works OK. Also, what kind of a cooler do you have? The blinking might appear when the PI is thermal throttling(not being able to decode frames as fast as needed).

A few people also had issues with metal cases blocking the signal...

I am making guesses right now, I've never experienced anything like this

**Comment by earthwormjimwow** [comment]
I have the same tower cooler you have, with just acrylic pieces to guard from shorting out the bottom of the PCB.

I'll try removing the overclock.

**Comment by earthwormjimwow** [comment]
Removing the overclock did not make a difference.  What seems to have resolved it is lowering the autokit FPS setting to 30, down from 60.

**Comment by earthwormjimwow** [comment]
@mikegapinski 

I think figured it out from your Twitter post talking about Bluetooth limitations with WiFi on a Pi.  I have been using Bluetooth tethering.  Bluetooth tethering + Carplay at 60FPS is probably running into bandwidth limitations.  So dropping to 30 FPS cut the required bandwidth I'm guessing, and the issue has not reappeared even with Bluetooth tethering enabled.
