### ISSUE TITLE
Bluetooth audio from the Pi

### ISSUE THREAD

**Issue by Hazmataz** [tesla-android/issue-tracker#113]
I can successfully connect via Bluetooth via the pi but getting the audio to route from the pi rather than the browser doesn’t seem to work. Is there an additional setting that needs to be set to force Bluetooth audio rather than browser audio? I want to play media from the pi rather than CarPlay or android auto

**Comment by mikegapinski** [comment]
Serving audio from the Pi over bluetooth is not possible with 44.1. I'll consider this for next updates
