### ISSUE TITLE
Overclock Pi

### ISSUE THREAD

**Issue by BroRidersMTL** [tesla-android/issue-tracker#115]
Im trying to overclock the Pi but my sharing & permissions "you have custom access" won't let me make the changes, im puzzled how to get around this

![image](https://user-images.githubusercontent.com/105889119/199292811-b651d490-f4c8-4049-bd9d-5598349127b0.jpeg)

**Comment by earthwormjimwow** [comment]
I had issues accessing the boot partition on my Windows computer, couldn't even assign a drive letter.  I just used a Linux VM which had no issue editing the config.txt file.

**Comment by mikegapinski** [comment]
It works fine on macOS, just use the TextEdit app. Windows on the other hand - no clue, not using it for ages now

**Comment by BroRidersMTL** [comment]
I did use the text edit app i can edit the text but then wont let me save it

**Comment by earthwormjimwow** [comment]
Maybe try launching text edit with elevated privileges (sudo).
