### ISSUE TITLE
Can not load in car, only with desktop computer

### ISSUE THREAD

**Issue by eknower** [tesla-android/issue-tracker#123]
Hi,
Was using Tesla Android from the first release, with great pleasure!

I just upgraded from the previous release. In my office everything works fine, but in my car I get a grey screen with the msg "Display service is unreachable, retrying..."
Tried rebooting, also tried car reset to delete cache

Any clue?

**Comment by mikegapinski** [comment]
There is a dedicated button for clearing the browser data in the service tab in your Tesla.
