### ISSUE TITLE
U-boot 

### ISSUE THREAD

**Issue by voyager-19** [tesla-android/issue-tracker#124]
Any clue why this appears when booting up the pi?
![image](https://user-images.githubusercontent.com/104236162/199627812-120f5a66-f32c-46c6-a8e0-f24a185befd9.png)

**Comment by mikegapinski** [comment]
something is wrong with the SD card... Did you use raspberry pi imager? I would try to download the image again and reinstall.

Card did not respond to voltage select might also indicate an issue with power, either a bad cable or a weak power supply

**Comment by voyager-19** [comment]
I used the Raspberry imager, downloaded & reinstalled, tried different SD cards, power adapters (even raspberry), and even four different computers.
