### ISSUE TITLE
Android App Problems

### ISSUE THREAD

**Issue by copperlab** [tesla-android/issue-tracker#127]
Having some problems with some of the android apps that I have installed.

Hulu - Can't login (I know login works because I am able to login on Disney+)
Netflix- Blank black screen
Audible - Blank black screen when clicking Sign In

**Comment by mikegapinski** [comment]
I am aware of this, the apps are blocking the screen capture, the same thing will happen if you open the app on an Android smartphone and start recording the screen. 

It will get fixed on a lower level by removing the Android API that is used by the apps to block the capture ;)

**Comment by mikegapinski** [comment]
Fixed in 2022.45.1 - all apps that need google play services will work + DRM content will is visible on the virtual display
