### ISSUE TITLE
Virtual Touchscreen is not active.  Wait for Android to boot up.

### ISSUE THREAD

**Issue by rrmills7777** [tesla-android/issue-tracker#136]
Whenever I login to the Tesla Android page (9.9.0.1), there is a splash banner across the bottom with the message "Virtual Touchscreen is not active.  Wait for Android to boot up."  Everything else seems to work fine.  Not sure if this is an issue or not.

**Comment by mikegapinski** [comment]
Fixed in the flutter app, that message was wrong, leftover from the dual board stack when touch was handled by Android and video capture was handled for linux.

https://github.com/tesla-android/flutter-app/commit/05174d6dba05bd8fcd9dcb8dd963b3c3b4578a34
