### ISSUE TITLE
Android auto choppy audio 

### ISSUE THREAD

**Issue by paulharman** [tesla-android/issue-tracker#137]
The audio is not smooth for android auto. 

Samsung S21
8gb pi 4 with overclock settings from guide
Tower cooling fan 
Carlinkit audio set to bluetooth

**Comment by mikegapinski** [comment]
Android Auto is not well supported by the dongle. Considering that this platform is more open Tesla Android will support wireless AA without the dongle at some point.

Right now there is nothing I can do about this, AutoKit is closed source and Carlinkit as a company ignores the issues we report to them.
