### ISSUE TITLE
Android auto resolution 

### ISSUE THREAD

**Issue by paulharman** [tesla-android/issue-tracker#138]
I'm guessing there's nothing you can do as the carlinkit resolution is fixed but in full screen the resolution is stretched so circles are oval

**Comment by mikegapinski** [comment]
Android Auto is not well supported by the dongle. Considering that this platform is more open Tesla Android will support wireless AA without the dongle at some point.

Right now there is nothing I can do about this, AutoKit is closed source and Carlinkit as a company ignores the issues we report to them.

**Comment by ca-dmin** [comment]
In case someone more experienced would like to try:

As a workaround I was trying to install android auto directly on the RPI4.
Installed [Android Auto](https://play.google.com/store/apps/details?id=com.google.android.projection.gearhead) and [Headunit Reloaded Trial](https://play.google.com/store/apps/details?id=gb.xxy.trial) via Aurora Store.

On my mobile this combination works; but not on the RPI4 - the screen shows just black :-(
