### ISSUE TITLE
Carplay frequent disconnects

### ISSUE THREAD

**Issue by rrlevy** [tesla-android/issue-tracker#146]
Since 2022.44.1 I'm having issues with frequent disconnects of CarPlay. (using CPC200-Autokit)

I get the message to "insert the product" meaning that the dongle would be disconnected, but it is properly connected to the USB port of the Raspberry Pi.

While trying to debug this, I tried:

1) Rebooting the iPhone: didn't fix it
2) Powering the Raspberry Pi from different places: I tested the glovebox USB, the central console USB, and also a 12V car USB charger of 30W
3) Using wireless and wired Carplay: same behavior
4) Multiple USB ports on the Pi.

However, while testing at my desktop PC, powered by a 12W USB charger it works for several hours without interruption.... It only happens in the car.

I still need to try:

- New Dongle (CPC200-CCPA)
- Removing and reinstalling the Autokit app

However, it seems to be a power issue related to the dongle or the car... I'm not sure what else to do.

**Comment by rrlevy** [comment]
If anyone know the procedure to remove and reinstall the Autokit Android App, please let me know

**Comment by mikegapinski** [comment]
The auto kit app is not installed as a system service, you can uninstall it from the settings app. 

Regarding power... Maybe it's an interference issue in the car or the dongle is somehow damaged? I have like 6 pi boards and both CPC200-CCPA and CPC200-AUTOKIT, no problems :/
