### ISSUE TITLE
Won't boot from USB

### ISSUE THREAD

**Issue by rrmills7777** [tesla-android/issue-tracker#147]
I have a fast low-profile thumb drive that I'd like to boot from instead of the microSD slot.  It starts trying to boot, then dies with "Unexpected XHCI event TRB, skipping..." and then boot loops on that.  Can USB boot be supported for this?

**Comment by mikegapinski** [comment]
USB boot is not supported by the bootloader used by Android

**Comment by jysaloma** [comment]
@mikegapinski  There is a vanilla image that can be booted via USB SSD / M.2 without sdcard
https://konstakang.com/devices/rpi4/AOSP13/ 

you need to change in /boot/config.txt 
#dtoverlay=android-sdcard
dtoverlay=android-usb

can you have a look at that as option? SSD option would make this so much faster to deploy and run.

**Comment by mikegapinski** [comment]
I don't use the kernel/device tree from KonstaKang. He doesn't have uboot and A/B support in Android. 

I expect to support USB, NVME and EMMC boot in Tesla Android sooner than later:)

**Comment by jysaloma** [comment]
Great we will be thankful ;)

**Comment by jysaloma** [comment]
Any progress on usb boot with ssd?
