### ISSUE TITLE
The projects web page doesn’t take people to issue tracker

### ISSUE THREAD

**Issue by electricAntEater32** [tesla-android/issue-tracker#148]
Hi the links in tesla-android main webpage for reporting issues doesn’t take people to the issue tracker . I get a report of missing webpage. 

https://github.com/tesla-android/tesla-android.github.io/issues/new

**Comment by mikegapinski** [comment]
Thanks! Fixed that: https://github.com/tesla-android/tesla-android.github.io/commit/f01ab83566f3e70d5dfe754673c18df43e333df8
