### ISSUE TITLE
Can not install apps from playstore in Tesla Android

### ISSUE THREAD

**Issue by sw1002** [tesla-android/issue-tracker#151]
It is not possible to install apps from google app store like youtube etc 

running the newest build though

**Comment by mikegapinski** [comment]
Fixed in version 2022.45.1 - google play is available, you will be able to sign in. If something would not show up in the store just grab the app from apk mirror

**Comment by ca-dmin** [comment]
@sw1002 
My workaround to get more apps: 
I was using Aurora Store. 
Has some problems, but it works.

Just a few notes I documented here:
https://github.com/ca-dmin/tesla-android-notes

**Comment by sw1002** [comment]
Sweet. Can I contribute to your notes?

**Comment by ca-dmin** [comment]
Of course. 
I am very interested in what others are doing. :-)
Easiest with merge request, issue, ... 👍
