### ISSUE TITLE
2022.45.1 install guide (single image) mentions overlocking without providing overclock settings.

### ISSUE THREAD

**Issue by electricAntEater32** [tesla-android/issue-tracker#159]
Hi, are overclock settings supposed to be removed from install documentation?

The 2022.45.1 install guide (single image) mentions overclocking the pi if CarPlay seems jittery. However in this release, the actual overclock settings are not mentioned. The  install guide (manual method) doesn't mention overclocking at all. Docs need updating?

**Comment by mikegapinski** [comment]
I need to remove that overclock mention, I removed the overclock settings section with this release

**Comment by devosthomas** [comment]
So no need anymore to overclock?

**Comment by mikegapinski** [comment]
I don't do it, there are more disadvantages to and you don't gain a lot

**Comment by mikegapinski** [comment]
Overclock is not recommended any more, I am not going to mention it on the www
