### ISSUE TITLE
2022.45.1 Can't install the Image

### ISSUE THREAD

**Issue by LeeCoxMS** [tesla-android/issue-tracker#160]
Loading the Image with RaspberryPi Imager on Windows 11. Using the same equipment as previously produces an error. It can't write the image file. Downloaded the image 3 times, Formatted the SD Card 3 times. Same result.

**Comment by electricAntEater32** [comment]
What install method are you using? Single image or manual method?  What is the name of the file you downloaded?

what size SD card are you using?

**Comment by LeeCoxMS** [comment]
Single Image, tesla-android-2022.45.1-single-image.img, 64GB SD-Card that was running 2022.44.2

**Comment by electricAntEater32** [comment]
Thanks. I don’t have Win 11 but I can try later today using Win 10 to setup my secondary pi that I use for testing. Last night I used macOS to setup my “daily driver” pi.

**Comment by LeeCoxMS** [comment]
I have a MacOS VM running on my main system. Worked just fine with the tesla-android-2022.45.1-single-image.img package. Seems to be something with the image file and the Windows Imaging tool.

**Comment by paulharman** [comment]
I had the same issue on multiple devices (error was file size could not be restored).  Ended up having to use Balena Etcher

**Comment by galosre** [comment]
For me also  NoNO with the Raspberry Pi Imager I used Rufus no PB after it  https://rufus.ie/en/

**Comment by electricAntEater32** [comment]
@mikegapinski  , hm perhaps in documentation it should mention that Windows users try using  Balena Etcher or Rufus if there are issues writing the single image to micro sd when using Raspberry Pi Imager?  Raspberry Pi Imager might've a bug right now.

**Comment by mikegapinski** [comment]
I'll leave it as is, I removed the reference to Etcher a while ago when people were having problems with it. The single image install method will improve soon, right now the image is too big and can sometimes be problematic to install
