### ISSUE TITLE
While installing 2022.45.1, keep getting the error during flashing process "Error extracting archive : File Size Could not be restored"

### ISSUE THREAD

**Issue by mguliani** [tesla-android/issue-tracker#174]
While installing 2022.45.1, keep getting the error during flashing process "Error extracting archive : File Size Could not be restored". I have tried multiple times but keep getting the error. I have extracted the archive separately, and that works fine but flashing from archive to the sd card keeps giving this error.

**Comment by rrmills7777** [comment]
Same problem here.

**Comment by AlexNoop** [comment]
i have extracted the zip and flash img,  it's working now !

**Comment by jirijanata** [comment]
I changed the documentation (and I opened a Pull Request) and I added a point, that zip extraction is needed. This issue can be then closed.
