### ISSUE TITLE
2022.45.1 CarPlay Nav Audio becomes muted more frequently than previous builds

### ISSUE THREAD

**Issue by electricAntEater32** [tesla-android/issue-tracker#176]
Hi all,

For me, often when using CarPlay maps in tesla-android 2022.45.1 , the nav audio from CarPlay will work initially but soon becomes muted (not heard at all). For example, I'll have a podcast playing, start maps navigation. I'll hear spoken directions for a while but eventually the spoken directions are not heard. When this happens, if I click on Tesla bluetooth app and push pause/play and return to Tesla browser app to see Tesla-android then the spoken directions audio returns for a while. It seems like there are two audio streams and due to some actions in CarPlay, the audio stream for spoken audio gets shuffled around and hidden. An analogy, in visual effects tools when layers in a program like After Effects, Nuke or Photoshop get incorrectly arranged thus hiding parts of a composited image.

This issue was much less frequent in previous builds but did exist. I know versions of autokit bundled within Tesla-android can vary. So I'm unsure if this is an autokit issue or something else within Tesla-android. 

I'm using the version of autokit which comes with Tesla-android 2022.45.1 . Autokit says there is an update which I've not installed. My carlinkit box is using latest firmware. 

How to reproduce (usually):
1) Have no audio playing from podcast or music.
2) Start a route in CarPlay maps.
3) then start playing a podcast 

Other ways it happens
1) Start a podcast
2) start a route in apple CarPlay
3) select a different podcast to play or switch to music....
4) ok if above doesn't stop maps nav audio from being heard, just drive around a while and skip forward to new songs/podcast using steering wheel. 

Or perhaps this issue just happens in my car?

**Comment by mikegapinski** [comment]
Aware of the problem, I am almost done with the new capture component that will support DRM like the updated video layer. Baby steps 😅

**Comment by adamChrystie** [comment]
Today my carlinkit box was updated to firmware 2022.11.19.1218 . Now my Siri audio is perfect, no choppiness, no nav words occasionally totally skipped. Now Music / podcasts do not remain paused when Siri speaks due to “hey siri”.  When nav audio is spoken, the music/podcast volume is lowered so nav can be heard  more easily . Would be great if podcast audio was paused and resumed by nav audio.  My maps setting for that type of behavior is turned on. Not sure if tesla-android  can do anything about that though.

**Comment by adamChrystie** [comment]
Seems podcast audio is paused when spoken nav starts and unpaused when spoken nav finishes. Perfect.

**Comment by mikegapinski** [comment]
Fixed with AutoKit app & dongle firmware update
