### ISSUE TITLE
Argon Fan Hat

### ISSUE THREAD

**Issue by tregan01** [tesla-android/issue-tracker#178]
I bought the hardware that was recommended. Once I have 2022.45.1 installed, how can I enter terminal to write the script for the Argon Fan Hat, curl https://download.argon40.com/argonfanhat.sh | bash? Without it, the fan just continuously runs. Don't want it running if I leave the Raspberry Pi4 connected to the car while I'm not driving.

Thank you!

**Comment by mikegapinski** [comment]
The pi will sleep with the car, nothing to sorry worry about. 

You can permanently change the fan config in config.txt

dtoverlay=gpio-fan,gpiopin=18,temp=55000

This entry will turn on the fan only when the pi exceeds 55 degrees on the cpu core

**Comment by tregan01** [comment]
Thank you so much for getting back to me, and for developing the tools needed to get CarPlay working in a Tesla! Sorry if this seems frustrating, but I am quite new at this. In the config.txt I see 2 lines that begin with dtoverlay. One says, "dvtoverlay=dwc2", and the other says, "dtoverlay=vc4-kms-v3d. Am I replacing both lines with what you suggested? Thanks again!

**Comment by mikegapinski** [comment]
Don't replace anything, just add the line I mentioned above on the end of the file

**Comment by tregan01** [comment]
Thank you again! This is like Eddie Van Halen getting back to me and be like, 'No, no. Do it this way...". Ha! Ha!

**Comment by tregan01** [comment]
Again, my apologies, but it seems that, even with the line you mentioned above entered, the fan continues to run

**Comment by mikegapinski** [comment]
Oh... You have the argon fan hat, I have the Argon Mini Fan, this config might not work for this :/

**Comment by tregan01** [comment]
Ha! Ha! I bought that because you had had that listed as one of the ones you recommended, on a previous version. Oh well.

**Comment by tregan01** [comment]
Just wanted to clarify, I see there are several "context.txt" files. Am I entering that script in the first one (only marked context.txt, and not one of the other ones that have numbers and letters attached)? Thank you again!

**Comment by KBD77** [comment]
> Again, my apologies, but it seems that, even with the line you mentioned above entered, the fan continues to run

Have you managed to control fan speed? I have the same fan

**Comment by tregan01** [comment]
You have what same fan, the fan hat or the mini? I returned my fan hat, got the mini, entered the code, and it works fineSent from my iPhoneOn Mar 15, 2023, at 2:40 PM, KBD77 ***@***.***> wrote:﻿

Again, my apologies, but it seems that, even with the line you mentioned above entered, the fan continues to run

Have you managed to control fan speed? I have the same fan

**Comment by mikegapinski** [comment]
Took a brief look on the script and how this particular fan is controlled - this overlay won't work for this fan since it's not driven with just PWM.

There is another cooler that works with PWM: https://www.waveshare.com/wiki/PI4-FAN-PWM

I tested the twin made for the Compute Module 4 and it's awesome, transfers heat very well and it's good for slim cases.

I'd close this issue, not much I can do here
