### ISSUE TITLE
Www page Hardware list update: Add warning about USA Alcatel modems 

### ISSUE THREAD

**Issue by electricAntEater32** [tesla-android/issue-tracker#184]
@mikegapinski , There should be a warning in suggested equipment list about North American Alcatel modems sometimes not working with tesla-android due to two different hardware variants & no way to know which variant is being sold by store.

Might be nice to link to below instructions on how to use the modem with TP-Link TL-WR902AC travel router if person has the unsupported modem and want to use it with pi via a travel router. I plug my pi and router in to 12v 160watt cigarette adapter, no problem. 

https://teslamotorsclub.com/tmc/threads/carplay-solution-for-tesla-by-michal-gapinski-using-raspberry-pi-with-android.281429/page-17#post-7180202

**Comment by mikegapinski** [comment]
@electricAntEater32 I'll just adding a small note about the M2M variants, the new version will switch it to the proper mode automatically on boot

**Comment by mikegapinski** [comment]
This is not longer a problem, 2023.4.1 will automatically convert the modem to rndis
