### ISSUE TITLE
Tesla firmware 2022.44.2 broke audio from tesla web browser?

### ISSUE THREAD

**Issue by adamChrystie** [tesla-android/issue-tracker#189]
I posted this [issue in reddit ](https://www.reddit.com/r/teslaandroid/comments/zj4b2c/tesla_firmware_2022442_broke_audio_from_tesla_web/?utm_source=share&utm_medium=web2x&context=3)and got confirmation another user has same issue. 

Ever since updating to tesla firmware 2022.44.2 in my 2022 Performance Model Y, I have noticed that I get no tesla browser audio from tesla-android . To test I used the default web browser & Firefox to play audio from theonion.com & npr public radio. Video worked. No audio.  During my test I unplugged carlinkit dongle & killed autokit app. Then I turned off tesla-android and tried the Tesla browser, same result no audio even when in park mode.

I think there is one more Tesla vehicle firmware update coming in December. Perhaps this will fix the issue?

**Comment by mikegapinski** [comment]
I am hoping to address this in the holiday update.

First I need my new audio capture module to be finished. The current solution sucks so much that I can't blame this on 44.2 honestly.

**Comment by adamChrystie** [comment]
Looking forward to new audio capture module. I hate computers sometimes. Soooo, I got tesla browser audio working again. Not exactly sure how. I tried various audio sites in tesla browser, none worked. I went in to service mode and was going to reinstall Tesla firmware but I got too scared. I exited service mode. Then I loaded YouTube via Tesla theater. YouTube audio worked. I used the minimize button which shrinks YouTube in to browser size window. I exited YouTube. I loaded browser and now browser audio started working. I think playing YouTube in theater app somehow restored browser audio. Now big question is does my CarPlay nav voice return to being choppy and often missing or remain crisp and clear. I suspect now that browser audio is working, I’ll get choppy nav audio again since audio capture module will be activated somehow. I’ll read that code sometime, seems interesting. Just for learning.  tomorrow morning I’ll see what nav audio quality I end up with. 🤣

**Comment by adamChrystie** [comment]
Hi all. I'll close this issue. The below is [from tesla-android Reddit](https://www.reddit.com/r/teslaandroid/comments/zj4b2c/comment/izxbmdc/?utm_source=share&utm_medium=web2x&context=3). 

Drove car today. Although tesla web browser audio is working again, glad to say CarPlay nav voice is still crystal clear like it became after recent carlinkit box (hardware) firmware update. I’ve been using tesla-android everyday for about 3 months & this is first time issue happened but it was easy to fix. In future if playing YouTube in Tesla car's Theater app doesn’t work, I’ll try reboot of Tesla car's computer and then the other advice in reply below.
https://www.reddit.com/r/teslaandroid/comments/zj4b2c/tesla_firmware_2022442_broke_audio_from_tesla_web/izw7g7i/?utm_source=share&utm_medium=ios_app&utm_name=iossmf&context=3
