### ISSUE TITLE
Instructions should inform users to connect to wifi Tesla-Android_XXXX 

### ISSUE THREAD

**Issue by adamChrystie** [tesla-android/issue-tracker#193]
I thought the instructions said at one point to connect to wifi network name Tesla-Android_XXXX  (where X's are numbers). But I do not see that anymore. This caused a user to make a help request. Perhaps in future documentation this info can be added again. 
[Reddit thread](https://www.reddit.com/r/teslaandroid/comments/zomxb2/comment/j0qo0z7/?utm_source=share&utm_medium=web2x&context=3) where this issue was identified.

@mikegapinski is there an active preview / dev branch I should look at to see if any documentation updates are needed? I could make changes and make a PR. Just wanted to get the best branch to look at in the event you had been updating documentation. However, if you do not need any help in the area that's ok. Just offering to take some typing off your hands.

**Comment by mikegapinski** [comment]
I update the website right after I finish the build. If you feel that something is missing in the tutorial/notes fork the repo, make changes on a branch and submit a pull request, I'll merge it before a new version comes out. I don't expect to change a lot on the www, the install process will look the same (some small changes in manual install page).

Thanks for your help!
