### ISSUE TITLE
Newest version 2023.4.1.1 Screen blinks sometimes, shows error

### ISSUE THREAD

**Issue by Ujorontti** [tesla-android/issue-tracker#206]
Hello 

I am running tesla android version 2023.4.1.1 on RP4 4g on my Model 3 software version 2022.44.25.3.
Older version of this TeslaAndroid was working ok, except slow response times, have to move it closer to right mirror.
But now this newest version blink screen randomly, and shows "Display service is unreachable retrying", just fast blink and it works again does this all time.
Made fresh install to memory card.
Is this known bug o this ?
Try to put picture here.
![IMG_4562](https://user-images.githubusercontent.com/122857905/214499301-6d110756-9fe9-446c-bac9-8d300c0094f5.PNG)

**Comment by mikegapinski** [comment]
Install 2023.4.2

**Comment by Ujorontti** [comment]
Thanks fast answer, try this when link starts working now it gives error 503 backend unavailable .

**Comment by mikegapinski** [comment]
the links in https://teslaandroid.com/install-guide work fine
