### ISSUE TITLE
Not hearing me after initial responds to "okay Google"

### ISSUE THREAD

**Issue by bplayabball** [tesla-android/issue-tracker#207]
Currently using single board with latest version. Got the latest carlink dongle and update it to the latest firmware. I'm able to hear my music (Android phone) but I'm not able to hear new text messages or being able to use okay Google. It brings the interface up, but it is not hearing my voice. Any ideas?

Edit: When I say "Okay Google" it brings up the interface, but mic goes away after that. I have tried car and phone as bluetooth source, but nothing. This is on the latest Android 13 image.

**Comment by mikegapinski** [comment]
AutoKit works OK with CarPlay, Android Auto is a hit or miss. If you just purchased the dongle - return it. You can achieve Wireless Android Auto without any dongles with Headunit Reloaded from the PlayStore(the paid one, trial does not work no idea why). Just make sure to disable the Audio Sink in its settings.

I'll remove the mention of Wireless Android Auto from the hardware list, there is no need for the dongle.

**Comment by bplayabball** [comment]
> AutoKit works OK with CarPlay, Android Auto is a hit or miss. If you just purchased the dongle - return it. You can achieve Wireless Android Auto without any dongles with Headunit Reloaded from the PlayStore(the paid one, trial does not work no idea why). Just make sure to disable the Audio Sink in its settings.
> 
> I'll remove the mention of Wireless Android Auto from the hardware list, there is no need for the dongle.

I will see about returning the dongle. As for Headunit Reloaded, do I sideload it on to Pi?
