### ISSUE TITLE
Tesla-Android Fork

### ISSUE THREAD

**Issue by MCFFHAB** [tesla-android/issue-tracker#209]
@mikegapinski I am happy that I could help on closing the IK41 Modem variant issue.  Your project is looking great.  I am thinking of creating a fork of your project but with a slightly different intent.  I would like to create a minimalist version with only the absolute minimum functionality for Apple CarPlay only - no video requirement, no Android Auto, no OTA, no etc...  I also would like to go back in Android version as far back as possible so I get a smaller footprint but still having the functionality for CarPlay - After a quick look on Android versions I am assuming I would need to use Android 6 (which includes support for USB-C and higher resolution display, or Android 5 with additional patches? Is that correct?  Also, do I need to use Flutter or can I code everything that is Flutter in C?  I am assuming that Flutter is also adding some weight with its libraries.  Last but not least, if I could use Android 6 or Android 5 (if either can support CarPlay) can I still use your Project as a fork to generate the images without too much changes or will this require major surgery?  Thank you for your help.

**Comment by mikegapinski** [comment]
Older versions of Android are not supported by the hardware...

If you want only CarPlay I would suggest using linux with something like this: https://www.npmjs.com/package/node-carplay

There is only one thing missing in this library, it does not set Audio Source to bluetooth in auto kit and you would need to find out how to do it by researching the protocol
