### ISSUE TITLE
2023.4.2 intel glitches/artifacts

### ISSUE THREAD

**Issue by dapperdal** [tesla-android/issue-tracker#211]
i have been using the new release, thank you for your hard work!  the new version doesnt have glitches on the intel hardware on model 3 to start with, after a few moments blocks appear and pink/grey blocks.  you have to click off and click onto something else to make the screen come back.  tried reboots and also clearing history.   I think this is related to the refresh, i did try 60fps, seems worse.  30fps was still bad though.   i was on a few hours journey then had to stop using it for the navigation

**Comment by mikegapinski** [comment]
It has nothing to do with intel, it's an issue with the hardware encoder on the pi and it has been mentioned in release notes. It'll be resolved in the next release

**Comment by dapperdal** [comment]
Thanks, sorry didn’t see in the notes.  Thanks for the response Sent from my iPhoneOn 31 Jan 2023, at 8:21 am, Michał Gapiński ***@***.***> wrote:﻿
It has nothing to do with intel, it's an issue with the hardware encoder on the pi and it has been mentioned in release notes. It'll be resolved in the next release
