### ISSUE TITLE
Argon One Pi4 v2 Case with Fan

### ISSUE THREAD

**Issue by jbredcar** [tesla-android/issue-tracker#213]
This aluminium case comes with a built-in variable-speed fan, but it runs constantly. 

I tried adding the line you suggested, but that doesn't seem to work.

There is a script for this fan here - http://download.argon40.com/argon1.sh

Is there any chance of integrating the fan part of the script please? I think that the defaults would work fine:

55C = 10% power
60C = 55% power
65C = 100% power

Thanks so much and I hope you received the coffees I sent?

John

**Comment by mikegapinski** [comment]
Hey!

If you can - return the case. Metal cases block the Wi-Fi signal from the Pi. It'll make your Tesla Android unusable. Use something plastic or open.

When it comes to Fan control. The only way to achieve this uses the official kernel config method.

Add this to /boot/config.xml

dtoverlay=gpio-fan,gpiopin=18,temp=55000

This will turn on the fan when the temp reaches 55, feel free to adjust the config

Thank you for supporting the project!

**Comment by jbredcar** [comment]
Hey Mike!

Thanks so much for this, do you recommend the Argon Mini Fan? It may be worth specifying this in the hardware list?

You mention "Open housing for Raspberry Pi 4". Is this a particular case that you recommend?
