### ISSUE TITLE
Issue with Alcatel Modem and Telecom operator that use IPv6 for tethering

### ISSUE THREAD

**Issue by rrlevy** [tesla-android/issue-tracker#217]
Hi, 

I digged a little deeper on my issue with the Alcatel modem and our telecom operator (Telefonica Vivo) here in Brazil and I found out a few things:

1) This telco is known for attributing an IPv6 for a second device when you have a mobile phone with a voice/data plan and you do a Wifi tethering.

2) Teslas won't work if assigned an IPv6. This has been checked with an iPhone of the same operator sharing Wifi with the Tesla. The car won't connect 

3) When using Tesla Android with the Huawei Modem, both the Android device and the Car can get a functioning internet connection

4) When using Tesla Android with the Alcatel Modem (with the same SIM), the Android device will have functional internet access, but the Car won't.

5) When accessing https://test-ipv6.com and https://ipv6test.google.com/ with the Android browser with the Alcatel modem, it will show that the Android has both IPv6 and IPv4 and it will navigate correctly. However, the car has no Internet and I can't make no checks. I can only correcly access the flutter app at 9.9.0.1.

Screenshots of both IPv6 tests:
![image](https://user-images.githubusercontent.com/14061585/217343529-5ad8569d-ede0-4331-8c14-bcf2db7df4c9.png)

![image](https://user-images.githubusercontent.com/14061585/217343512-2b2505c0-ae8c-412c-aaba-140d5942c646.png)

Isn't there anything that can be done on the Android project to make sure it only uses IPv4? It seems the conflict is arising from the fact that Android has functioning IPv6.

On the old Alcatel issue, @mikegapinski mentioned that Android was not compatible with IPv6 on USB modems, but the screenshots above shows that the IPv6 is being assigned on the Alcatel Modem and the Android system is using it on web navigation

These tests were made in Tesla Android version 2023.4.2

**Comment by bbetter173** [comment]
Have you tried disabling IPV6 support in Raspbian? You can add these lines to `/etc/sysctl.conf` and reboot to try:

```
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
```

**Comment by mikegapinski** [comment]
On linux I would normally use:
net.ipv6.conf.all.disable_ipv6=1
net.ipv6.conf.default.disable_ipv6=1
net.ipv6.conf.lo.disable_ipv6=1

to disable ipv6 fully. @rrlevy would disabling ipv6 in Tesla Android resolve this issue? I might give it a shot

**Comment by rrlevy** [comment]
It most likely would solve it!

And it is relevant for all, since Tesla cars won't work with ipv6.

Can I do something to test that on a builded version?

**Comment by mikegapinski** [comment]
Modem related, e3372 shipped with the bundles has an option to force ipv4 regardless od carrier preference
