### ISSUE TITLE
No audio output when streaming to Tablet/other device

### ISSUE THREAD

**Issue by sw1002** [tesla-android/issue-tracker#226]
I want to view the TeslaAndroid virtual screen simultaneously on my MCU2 and on a tablet in the second/third row. When I connect to the hotspot with my iPad I get the video payed back but no audio. Do I handle something wrong?

**Comment by mikegapinski** [comment]
Safari does not support the audio sadly. Thank Apple. BTW: you can play the audio via the car infotainment; no need for the iPad

**Comment by sw1002** [comment]
Would another browser be possible?Am 23.02.2023 um 09:09 schrieb Michał Gapiński ***@***.***>:﻿
Safari does not support the audio sadly. Thank Apple. BTW: you can play the audio via the car infotainment; no need for the iPad
