### ISSUE TITLE
Argon Case Poweron Question

### ISSUE THREAD

**Issue by maxicusj** [tesla-android/issue-tracker#243]
Hi Michal,

Kudos for the super job!
One quick question - i got an older argon case with the power button, that needs to be manually triggered on each time in the car. New cases have jumpers, older could be set via the shell command:

i2cset -y 1 0x01a 0xfe 

to autopower on. How do i get into shell to run the command enable auto power on?

thank you,
Roman Max

**Comment by mikegapinski** [comment]
You can get shell(with root) using adb. adb root && adb shell. Later you'd need to cross compile i2cset with Android NDK, push it to the device and execute normally. Same path I took with the web server; iOS tethering support via usbmuxd etc.

There is no way to just use i2c-tools from raspbian; android won't run those binaries unless they were compiled with the proper toolchain.

I've found something that could work if you manage it to build: https://github.com/NHellFire/busybox-android-ndk/blob/master/miscutils/i2c_tools.c
