### ISSUE TITLE
Wifi disconnecting and not accepting password

### ISSUE THREAD

**Issue by Ujorontti** [tesla-android/issue-tracker#251]
Hello

I have Teslaandroid on my Car all-time on, running version 2022.27.1. Tesla version 2023.6.8 Model3 Perf 2020
Sometimes when I go to my car, Wifi is not connected, can see that wifi is there, if try to connect, tells wrong password.
If try to give right password, it doesn't accept it, even if I try to connect with my phone.
After I boot Raspberry, car connects without problem, without changing anything.
Any idea, what might cause that?
Boot takes so long time, that's why I leave it running.(Wife telling too long :) )
Or do I have to change Wife or start shutting Raspberry down when leave car?

**Comment by mikegapinski** [comment]
Boot will take like 3x less time in the next build. I would not recommend leaving the pi on 24/7, especially if you don't have the LTE modem, the car won't connect to the mothership in this case.
