### ISSUE TITLE
What other devices is it possible to run the software on?

### ISSUE THREAD

**Issue by DrKoneko** [tesla-android/issue-tracker#259]
I installed the project on my RPI4, but I realized that my RPI is the 1GB model. With prices for even 4GB models being over 100$, do you know of any other boards or devices that you could run the project on? I have an old Google Pixel 3 that I could flash the ROM to but I don't know how to configure the ROM for other devices. I also just wonder if anyone else has run the project on an alternative board that's cheaper but works just as well. Let me know if anyone has tried running it on another android device or board and had success, and what I would need to do to achieve the same goal. Thanks!

**Comment by mikegapinski** [comment]
It won't run on anything else unless I decide to burn a few months to do the bringup on some other board. Android is device-specific and I rely rpi4-specific apis to make it work. 

BTW: it's not an issue, this tab is used to track bugs; not for general discussions
