### ISSUE TITLE
No Access in tesla official app After connecting to teslaAndroid Wi-Fi 

### ISSUE THREAD

**Issue by lobofoots** [tesla-android/issue-tracker#260]
Hello

I use teslaAndroid v 2023.18.1
I don't have premium connectivity in my tesla
My car is connected to teslaAndroid Wi-Fi from the RPi.

If I open the official Tesla app on my Android phone, my car is not found and I can't interact with it.

If I manually disconnect my car from the Wi-Fi, the Tesla app see my car again.

**Comment by mikegapinski** [comment]
If you don't have any internet connectivity in your Tesla Android setup(modem, tethering etc) your car won't be connected to internet. Thats obvious
