### ISSUE TITLE
MCU2 5GHz canal 

### ISSUE THREAD

**Issue by jirijanata** [tesla-android/issue-tracker#273]
Hello, according to this Page sees the MCU2 no canals under 100. I just tried to switch the wifi to 5 GHz, but the MCU2 in Model 3 2019 doesn’t see the Wifi. The Android is broadcasting 5 GHz Wifi on canal 36, which is too low. 

Can you change it somehow? In the Android settings it wasn’t possible. Thank you very much and have a nice day!

https://teslawissen.ch/tesla-wlan-empfang-verbessern/#5-ghz-wlan

**Comment by mikegapinski** [comment]
I am 100% sure that it works on even older cars. Even in Japan where those bands are in theory also not supported. I am using a global region on the network config, it is one of a few channels that work everywhere

There is however another caveat, those older cars have the Wi-Fi antenna on the outside, if your pi is far away from it it might not get the signal. 


Try rebooting the car to force the scan, I had to do it after switching the band when it remembered the network was 2.4 before.

**Comment by jirijanata** [comment]
Thank you very much for your quick reply. I just tried another hotspot from my notebook and it was showing in the Tesla - canal 149. I’ll try all the channels tomorrow. The raspberry is about 70 cm from the antenna, ao that shouldn’t be a problem. 

I also tried another Hotspot name and MCU reboot as you suggested. 

I have firmware 2022.12.3.2 because of NoA, so that can be also an issue.

Can you tell me which file should I edit before/after the installation to change the channel?

Thank you very much!

**Comment by mikegapinski** [comment]
It might not work on the older firmware. I had issues with 5GHz last year in the car. That is why I did not ship it before. The old firmware also does not have the current chromium version and this might be very problematic very soon.

**Comment by mikegapinski** [comment]
I have testers in Germany with MCU2 and I also have MCU2 in Poland. There is no "swiss" region for the car, it is either EU or North America etc.
