### ISSUE TITLE
Carlinkit Dongle CPC200-CCPA version gives "The product is not authorized, please contact the dealer"

### ISSUE THREAD

**Issue by devosthomas** [tesla-android/issue-tracker#28]
I bought a brand new Carlinkit CPC200-CCPA. When I plugged it in I got an updated message of new firmware. Installed the last update of the device to software 2022.04.15.0920 - box version 2022.04.25.1317 and I receive the message "The product is not authorized, please contact the dealer."

Any idea how to fix this? Do I need custom/modified firmware for the CCPA dongle?

**Comment by mikegapinski** [comment]
That should work out of the box. I am still waiting for my CCPA dongle to arrive, I will get back to you when I test it.

**Comment by devosthomas** [comment]
I downloaded the autokit.apk from https://www.carlinkit.com/en/download.html and installed it on the RPI4. 
This gives me software version 2022.04.29.1750 (newer than the autoupdate version). 

Good news: CarPlay and Android auto are now working via cable. Still have to check out how to make them wireless.

**Comment by mikegapinski** [comment]
Hey, I've tested the CCPA dongle briefly on my development build.

The APK included with the rom is for the older dongle. Uninstall it first and then install the apk that is included with the CCPA dongle using android built-in file manager. (CCPA exposes a fake usb thumb drive with autokit apk)
