### ISSUE TITLE
Latest version of Android Platform Tools needs to be installed

### ISSUE THREAD

**Issue by alternateal** [tesla-android/issue-tracker#3]
In the Install guide line 2 says: Make sure that both fastboot and adb is installed and accessible from your terminal.

This should be updated to say that the latest version of both fastboot and adb need to be installed and accessible from your terminal. They can be found here: https://developer.android.com/studio/releases/platform-tools

I spent 40 mins re-running the commands to find they kept failing on "fastboot reboot-fastboot" as the version of fastboot I was running didn't allow this.

**Comment by mikegapinski** [comment]
@alternateal thanks for the info, I've updated the guide
