### ISSUE TITLE
2023.38.6 - can’t connect to Raspberry wifi due to no connectivity

### ISSUE THREAD

**Issue by andrewsexcellent** [tesla-android/issue-tracker#307]
Hi,

My raspberry doesn’t have a 3G modem and i just updated my Model Y to 2023.38.6 where it seems like it’s no longer possible to connect to a wifi network that doesn’t have internet connectivity.

I’m on version 2023.42.1 of Tesla Android

Tried:

- Restarting the car
- Restarting the raspberry
- Reentering the password for the wifi

video attached 

https://github.com/tesla-android/issue-tracker/assets/82413230/be2be309-c102-4add-bbc1-33fca875139f

**Comment by Skitals** [comment]
Same here. Updated the car and can no longer connect to the teslaandroid wifi due to no internet.

Assuming no simple workaround, custom dns and http server should be able to satisfy the Internet check.

**Comment by mikegapinski** [comment]
I already have a DNS server with a spoofed connectivity check response in place. They must have changed something

**Comment by andrewsexcellent** [comment]
https://github.com/tesla-android/android-raspberry-pi/releases/tag/[2023.45.1](https://github.com/tesla-android/android-raspberry-pi/releases/tag/2023.45.1) Fixed it, nice job!
