### ISSUE TITLE
Expired SSL Certs

### ISSUE THREAD

**Issue by wyllys66** [tesla-android/issue-tracker#319]
The SSL certificate for device.teslaandroid.com expire on May 7 2024.  This affects all recent builds, including 2024.18.2

Subject: [device.teslaandroid.com](http://device.teslaandroid.com/)
Issuer: R3
Expires on: May 7, 2024
Current date: May 9, 2024

**Comment by mikegapinski** [comment]
Clear browser data, the new build has updated certs that last a year
