### ISSUE TITLE
Tesla Wifi Dropouts

### ISSUE THREAD

**Issue by Dazzert318** [tesla-android/issue-tracker#37]
All installed and deployed to vehicle which is a 2022 Model 3. I’ve tried using the system on 3 short trips of around 30-40 minute duration with Waze. On each occasion Tesla WiFi is disconnecting randomly from Tesla-Android and at that point the browser locks up. It looks like the WiFi on the Model 3 is turning off or going to sleep and when I try to reconnect the Tesla-Android will only re-establish a connection once I’ve rebooted the two RPi units. Does anyone have a fix or advice?

**Comment by ochompsky** [comment]
i have the same problem, the wifi antenna in the car is not very good
