### ISSUE TITLE
Tesla Browser shows scroll bar

### ISSUE THREAD

**Issue by rrlevy** [tesla-android/issue-tracker#54]
My Tesla Browser is showing a scroll bar when acessing the Tesla Android address:
![image](https://user-images.githubusercontent.com/14061585/175845260-ef07a4a8-d9ed-462b-8006-723e3476544e.png)

The scroll bar is always there, regardless of the Android app I use:
![image](https://user-images.githubusercontent.com/14061585/175845249-f17dbe44-6402-4300-9bc8-96a3441c709f.png)

**Comment by rrlevy** [comment]
Did anyone else had this error in their installs?

I tried reinstalling the Android system from scratch and nothing changed....

**Comment by mikegapinski** [comment]
It's an issue with a frontend app, will be rectified in feature builds

**Comment by mikegapinski** [comment]
Can you verify that this scroll bar is gone on 2022.27.1?

**Comment by rrlevy** [comment]
I’m away from home for a week. I will do that next week

**Comment by rrlevy** [comment]
Sorry for the delay. The scroll bar was gone on 2022.27.1.
