### ISSUE TITLE
microG Services can't log in to Google servers

### ISSUE THREAD

**Issue by rrlevy** [tesla-android/issue-tracker#59]
When using any app that needs to login to a Google Account using Android account information, microG can't log in to Google.
After completing all the steps com logging in, and authorizing the login with your MFA device, it shows an error that it can't connect to Google Servers:

![image](https://user-images.githubusercontent.com/14061585/176083347-e6397e51-a98f-4dbc-987a-2f393043bbbb.png)

The Google login inside Aurora Store works fine

**Comment by galosre** [comment]
I am getting into the same issue on my second install on the first one it was working, maybe google is blocking something now!

**Comment by galosre** [comment]
And not sure if it is related got also Android system 'There's an internal problem with your device even on brand new install
![2022-06-29_215318](https://user-images.githubusercontent.com/22267106/176599806-e1901e51-f7c6-4187-a78c-47efb2a8c286.jpg)
e

**Comment by rrlevy** [comment]
I didn't get that message of "internal problem"

But the problem with microG not logging into Google is quite anoying.... It renders all Google Apps on the Android system unusable, since you can't log into your account.

For example, I can't use the Youtube app, which was one of the reasons I was installing Tesla Android for...

**Comment by mikegapinski** [comment]
I figured out that Google added a new verification scheme for login at some point - instead of just approving the notification on your other device you also need to pick a number on the screen. This results in a error you've shown on the screen. 

The second time around a different authentication mechanism triggered and I was able to login successfully. Will see what can be done about this as this is quite bugging me as well 😅

**Comment by rrlevy** [comment]
For some reason I ALWAYS get the “pick a number” question…. I’ve tried at least half a dozen times…
I’ll check google settings to see if I can somehow change my two factor settings to change that

**Comment by Cooker44** [comment]
At the moment I can’t see all Google apps in either fdroid or aurora. What am I doing wrong in the settings of these apps?  Will look for google account addition, but YouTube, GMail etc not available.

**Comment by rrlevy** [comment]
> I figured out that Google added a new verification scheme for login at some point - instead of just approving the notification on your other device you also need to pick a number on the screen. This results in a error you've shown on the screen.
> 
> The second time around a different authentication mechanism triggered and I was able to login successfully. Will see what can be done about this as this is quite bugging me as well 😅

I just tried again, first by changing my two factor methods and later by completely disabling two factor authentication 

I still couldn’t log in. I always get the error message after logging in….

**Comment by rrlevy** [comment]
Still not working on 2022.38.1

![image](https://user-images.githubusercontent.com/14061585/193460585-3a1b659c-c7f2-4520-ad9b-9bddb7686585.png)

I do all the authentication steps perfectly (enter password, click the number on gmail app, accept terms) but at the end I always get this message.

**Comment by rrlevy** [comment]
Is this working for everyone else? Is it just me?

This is really bad for me since not able to login to google apps. At least the first version with Play Store I could have my account logged in on Youtube App

**Comment by Cooker44** [comment]
Agreed, this is problematic.  Doesn't affect CarPlay functionality of course, but limits functionality

**Comment by rrlevy** [comment]
Yes, I was excited about having a full Android system to use on the car, but at the end I'm limited to CarPlay.

It is AMAZING to have CarPlay, but it would be nice to make Android work correctly.

**Comment by mikegapinski** [comment]
There is an open issue with the gapps I used for this problem, I am just waiting for a upstream fix ;)

**Comment by rrlevy** [comment]
I googled a lot about this, and this worked for me:

1) DO NOT connect the device to the internet
2) Open "microG Settings"app and disable "Google device registration" 
3) Exit the microG app and force close it
4) Connect Raspi to the internet via cable or LTE Modem
5) Enter microG and try to log in to Google Account
6) It works!

![image](https://user-images.githubusercontent.com/14061585/199323141-62af952f-7e65-4c2f-930f-868392d1f5bf.png)


Note that you NEED to turn off device registration BEFORE trying to login the first time, or else it won't work. If you have already tried to login, you need to reinstall the system.

**Comment by rrlevy** [comment]
I haven't tested not doing it in this latest build. I went straight to disable device registration before logging in. I actually don't know if the bug was fixed, but this a solution

**Comment by MCFFHAB** [comment]
> I haven't tested not doing it in this latest build. I went straight to disable device registration before logging in. I actually don't know if the bug was fixed, but this a solution

On the latest build it does not work either and the process above also did not work for me.

**Comment by mikegapinski** [comment]
I've updated microG services in my latest internal build (2022.44.3), if this doesn't solve the problem I'll dig deeper with the next build, since now most things are working OK I have time to spare on smaller things

**Comment by mikegapinski** [comment]
Fixed in version 2022.45.1 - I removed microG. Notmal google apps are back, no need to register the uncertified device like in dual board builds.
