### ISSUE TITLE
Virtual touchscreen in not active

### ISSUE THREAD

**Issue by jackkorber** [tesla-android/issue-tracker#62]
After install is I got a Virtual touchscreen in not active message and the touchscreen does not work. I am able to use an Bluetooth to the android pi a move within the screen with a lot of lag. Any suggestions?

**Comment by mikegapinski** [comment]
You forgot to set the ip of the Android Pi to 3.3.3.50

**Comment by jackkorber** [comment]
Yes, forgot set android pi ip
