### ISSUE TITLE
Not available for Model Y

### ISSUE THREAD

**Issue by BleuRain** [tesla-android/issue-tracker#63]
Car:
Model Y

System Software Version:
v11.0 (2022.12.3.16 Odeb51535534)

Discribe:
When switching to D file, R file, the screen will freeze.

Is there any way to solve it？

**Comment by mikegapinski** [comment]
Your Tesla-Android Wi-Fi network needs to have a "Remain connected in Drive" setting enabled in Tesla OS. By default Tesla disconnects the network when changing gears.

You have the same System Software Version as I do, you should be good to go
