### ISSUE TITLE
USB Dongle LTE stick

### ISSUE THREAD

**Issue by smgraver1** [tesla-android/issue-tracker#8]
I can’t understand what the LTE stick is actually for. What is it used for in the procedure to make it work?

**Comment by gpeavy** [comment]
To go with this question. Is it possible to tether the Android Pi to a wifi hotspot for internet access?

**Comment by mikegapinski** [comment]
@smgraver1 the LTE stick is required for the car to connect to the Tesla Android Wi-Fi network, Tesla automatically cuts the connection when it senses that no internet is provided. When connected to Wi-Fi your car uses the data package to download software updates, download Spotify/Tidal songs. It essentially replaces the Premium Connectivity subscription.

@gpeavy No, this won't work

Please use the discussions tab when you are not actually reporting any bugs next time.
