### ISSUE TITLE
New viewport on Tesla firmware 2022.24.5?

### ISSUE THREAD

**Issue by rrlevy** [tesla-android/issue-tracker#83]
I noticed after the last update to Tesla car firmware 2022.24.5 that I have some vertical bars on the sides of the screen:

![image](https://user-images.githubusercontent.com/14061585/187230358-00dc7769-a965-4fbb-a261-21701aa69b3f.png)
![image](https://user-images.githubusercontent.com/14061585/187230384-69bcf51b-b2ad-4d5e-9c4f-3c9945791a8a.png)

Maybe the viewport has changed in this version? I'm sending the viewport info:
![image](https://user-images.githubusercontent.com/14061585/187230503-e0b8a17d-5ce1-4f39-a90a-47bd02b028ee.png)
(Model Y 2022, car firmware 2022.24.5)

**Comment by mikegapinski** [comment]
Thanks for the info, I'll make an update once my car gets 2022.24.5
