### ISSUE TITLE
My 2nd pi4 not loading

### ISSUE THREAD

**Issue by BroRidersMTL** [tesla-android/issue-tracker#87]
I have format/erased the microsd 3 times now and reloaded software for single board but cant get past this just a spinning circle

https://user-images.githubusercontent.com/105889119/193076784-179defb7-5070-4bd8-b2ec-84b25ce869a6.MOV

**Comment by elic1973** [comment]
I have the same issue... and did the same. also updated the firmware and replaced cables. Same resualt.

**Comment by BroRidersMTL** [comment]
I will get back to you after tonite i did cables as well next step switch the hdmi-csi-2 from the board that works

**Comment by BroRidersMTL** [comment]
Issue fixed brand new hdmi-csi-2 defective
