### ISSUE TITLE
Can't view Android in Chrome and Carlinkit CPC300-Autokit causes constant reboot

### ISSUE THREAD

**Issue by osb99** [tesla-android/issue-tracker#9]
When I connect to the Tesla Android network and access http://3.3.3.1/ it just displays a white screen on both Chrome and Safari, why is this?

Also, the Carlinkit device seems to be causing the android pi to startup then reboot after 10 seconds of being on the Home Screen. It has been fully updated and so has autokit.
<img width="2240" alt="Screenshot 2022-05-09 at 22 33 00" src="https://user-images.githubusercontent.com/69733374/167502691-d061df31-f85b-4a02-94f1-630577e01aa7.png">

**Comment by mikegapinski** [comment]
For reboots - check power supply to the Pi4
White screen - check if Capture interface is properly connected(http://3.3.3.1:8001/state)
