### ISSUE TITLE
Carplay Permanently Pausing Playback For GPS Audio Prompts

### ISSUE THREAD

**Issue by earthwormjimwow** [tesla-android/issue-tracker#91]
I'm unsure if this is an issue with Tesla-Android, or merely a limitation with the Autokit based Carplay adapters.

In iOS, each audio playback app (Podcasts for instance), has the option to permanently pause playback whenever a GPS Prompt, Alert or Notification plays, or can be set to resume immediately after the GPS sound is done.  

This works fine on every OEM Carplay setup I have used.  However it does not work with Tesla-Android and the Autokit based Carplay adapter I am using.  Playback is permanently paused, no matter what settings I select in iOS. Any time Waze, Apple Maps, or Google Maps play an alert, notification or navigation instruction;  I have to press play, to resume whatever song or podcast I was listening to.

Could this be due to navigation audio being routed through the Pi directly to the browser, while media playback is over Bluetooth?  Is there some other OS level setting in the Pi causing this?

Anyone else have this issue?

**Comment by earthwormjimwow** [comment]
Forgot to add, this is the adapter I am using:
https://www.amazon.com/gp/product/B08FT73V87/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1

CPC200-Autokit

**Comment by BroRidersMTL** [comment]
> Forgot to add, this is the adapter I am using:
> 
> https://www.amazon.com/gp/product/B08FT73V87/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1
> 
> 
> 
> CPC200-Autokit

Did you update the adapter

**Comment by earthwormjimwow** [comment]
Autokit was updated, but the adapter was not updated this week.  The download kept failing, servers would time out.

It was updated a couple of months ago though.

**Comment by earthwormjimwow** [comment]
> > Forgot to add, this is the adapter I am using:
> > https://www.amazon.com/gp/product/B08FT73V87/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1
> > CPC200-Autokit
> 
> Did you update the adapter

Autokit was updated, but the adapter was not updated this week. The download kept failing, servers would time out.

It was updated a couple of months ago though.

Is this a known/resolved issue on their end?

**Comment by BroRidersMTL** [comment]
> > > Forgot to add, this is the adapter I am using:
> 
> > > https://www.amazon.com/gp/product/B08FT73V87/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1
> 
> > > CPC200-Autokit
> 
> > 
> 
> > Did you update the adapter
> 
> 
> 
> Autokit was updated, but the adapter was not updated this week. The download kept failing, servers would time out.
> 
> 
> 
> It was updated a couple of months ago though.
> 
> 
> 
> Is this a known/resolved issue on their end?
> 
> 

Could be a defective one or maybe not 100% compatible

I have this one coming tomorrow i dont know if its the same as urs CarlinKit Wireless CarPlay Adapter Support Wireless CarPlay Wired Android Auto for Aftermarket Car Radio with Android System 4.4.2 or Above(Only Support Install Autokit app in Android Car Radio) https://a.co/d/7TAj6sX

**Comment by earthwormjimwow** [comment]
> > > > Forgot to add, this is the adapter I am using:
> > 
> > 
> > > > https://www.amazon.com/gp/product/B08FT73V87/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1
> > 
> > 
> > > > CPC200-Autokit
> > 
> > 
> > > 
> > 
> > 
> > > Did you update the adapter
> > 
> > 
> > Autokit was updated, but the adapter was not updated this week. The download kept failing, servers would time out.
> > It was updated a couple of months ago though.
> > Is this a known/resolved issue on their end?
> 
> Could be a defective one or maybe not 100% compatible
> 
> I have this one coming tomorrow i dont know if its the same as urs CarlinKit Wireless CarPlay Adapter Support Wireless CarPlay Wired Android Auto for Aftermarket Car Radio with Android System 4.4.2 or Above(Only Support Install Autokit app in Android Car Radio) https://a.co/d/7TAj6sX

It's the same thing, these are made by one OEM, and rebranded or resold by 3rd parties.  CPC200-Autokit is the model number.

I doubt it's defective, since this is way too specific of an issue/feature.

**Comment by rrlevy** [comment]
I also have the same issue, with my CPC200

All podcast apps pause the audio permanently on GPS audio prompts

Even Spotify that works fine with music will pause when listening to a podcast

My Autokit version is 2021.06 (it has all updates installed)

**Comment by mikegapinski** [comment]
Get in touch with Carlinkit, if enough people raise the issue they might fix it. 

There are two issues:
1. Navigation voice is not routed via bluetooth
2. The pausing audio after prompts

**Comment by earthwormjimwow** [comment]
I sent them an email, hopefully they understand the issue.

Just curious, why do we need media audio routed through Bluetooth, rather than passing it through the browser?  Is this a compression/quality issue?  I have a feeling the switching of audio is what causes iOS to pause playback.

**Comment by mikegapinski** [comment]
The audio switching between android and Bluetooth happens on the dongle side. It has nothing to do with Tesla android. 

We can’t pump all of the audio through the browser - only Bluetooth provides steering wheel controls and microphone for calls

**Comment by earthwormjimwow** [comment]
Ah okay, that explains why we are using Bluetooth for the media audio path.

I was able to finally update the dongle's firmware.  I had forgotten to overclock the Pi, which was causing internet connections to time out constantly.  Working much smoother now with the conservative overclock settings you posted, and that Pi tower cooler.  However, still has the same media pausing issue, which is out of Tesla Android's control.

I'll post an update if I hear back from Carlink.

**Comment by mikegapinski** [comment]
Hey, did you see any fixes with updated auto kit apk? For me the recent version does not pause for navigation prompts. Apple Maps + Apple Music combo

**Comment by earthwormjimwow** [comment]
I'll test it out later today, I have been leaving Waze muted.

**Comment by earthwormjimwow** [comment]
Issue persists even with autokit updated.

**Comment by mikegapinski** [comment]
Fixed with AutoKit & dongle firmware update

**Comment by earthwormjimwow** [comment]
Confirmed, is resolved in the latest update as of 2023.
