### ISSUE TITLE
No browser audio on single board stack

### ISSUE THREAD

**Issue by rrlevy** [tesla-android/issue-tracker#92]
I have been using Tesla Android since the start.

However, when switching to the single board stack it seems that the browser audio is no longer working

The car won’t play my GPS prompts (although my podcasts are paused)

I couldn’t test the audio on other Android apps since the LTE also doesn’t work with the new version

Does anyone else have this issue? Does anyone have an idea on how to test the audio directly on the Android without Internet?

**Comment by mikegapinski** [comment]
Do you have a red icon in the status bar? If not: tap the audio capture app and reload the browser. It works fine, I use it every day

**Comment by rrlevy** [comment]
Yeah, I just connected an ethernet cable at home and tried the Android browser with audio. It works. It seems that only the GPS audio is not working, but I'll do further testing

**Comment by rrlevy** [comment]
I updated the Carlinkit software with the Ethernet cable and now it works! Thanks
