### ISSUE TITLE
carplay for rooted teslas? avoid owning a raspberry pi?

### ISSUE THREAD

**Issue by Geczy** [tesla-android/issue-tracker#93]
can a rooted tesla run the necessary carplay binaries? this avoids the wifi / raspberry pi / hdmi setup. the software will run directly on CID

is this feasible?

**Comment by mikegapinski** [comment]
it might be, but I don't have a rooted car to start tinkering with it. I would love to try if it won't void my car warranty

**Comment by Geczy** [comment]
> it might be, but I don't have a rooted car to start tinkering with it. I would love to try if it won't void my car warranty

how can i reach out to you? there's several options here. add me on discord? luckyrobot#0001
